server {
    listen 80;
    server_name nilo.luchang.xyz;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name nilo.luchang.xyz;

    ssl_certificate /etc/letsencrypt/live/nilo.luchang.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nilo.luchang.xyz/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|webp|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
