services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        VITE_WEBTRANSPORT_URL: https://localhost:4433/webtransport
        VITE_CERTIFICATE_HASH: ded2563223766b2f6b61179c544fc3984a34e678aded1438f4316b837af45050
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/certs/localhost.pem:/etc/letsencrypt/live/nilo.luchang.xyz/fullchain.pem:ro
      - ./server/certs/localhost-key.pem:/etc/letsencrypt/live/nilo.luchang.xyz/privkey.pem:ro
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      PORT: "4433"
      TLS_CERT_FILE: /certs/localhost.pem
      TLS_KEY_FILE: /certs/localhost-key.pem
    volumes:
      - ./server/certs:/certs:ro
    ports:
      - "4433:4433/udp"
    restart: unless-stopped
