services:
  client:
    image: ghcr.io/xfcced/nilo-demo-client:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

  server:
    image: ghcr.io/xfcced/nilo-demo-server:latest
    environment:
      PORT: "4433"
      TLS_CERT_FILE: /etc/letsencrypt/live/wt.luchang.xyz/fullchain.pem
      TLS_KEY_FILE: /etc/letsencrypt/live/wt.luchang.xyz/privkey.pem
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "443:4433/udp"
    restart: unless-stopped
